name: bineo
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  uuid: ^4.4.0
  dio: ^5.4.3+1
  lottie: ^3.1.0
  equatable: ^2.0.5
  local_auth: ^2.2.0
  seon_plugin: ^3.0.0
  geolocator: ^11.1.0
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  get_ip_address: ^0.0.7
  cupertino_icons: ^1.0.6
  native_dialog_plus: ^1.0.3
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  flutter_form_builder: ^9.2.1
  firebase_remote_config: ^4.4.5
  flutter_libphonenumber: ^2.2.2
  pinput: ^4.0.0
  sms_autofill: ^2.3.1
  flutter_secure_storage: ^9.0.0
  app_tracking_transparency: ^2.0.5
  flutter_keyboard_visibility: ^6.0.0
  flutter_carousel_widget: ^2.2.0
  syncfusion_flutter_pdfviewer: ^24.2.8
  path_provider: ^2.1.3
  onboarding_flutter_wrapper:
    path: ../IncdOnboardingFlutter
  dart_levenshtein: ^1.0.1
  url_launcher: ^6.2.6
  device_info_plus: ^9.1.2
  skeletonizer: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/svgs/
    - assets/images/
    - assets/animations/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
